# Generated by Django 5.1.2 on 2024-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, max_length=255, verbose_name='Available Colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Available Sizes'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Product Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_aed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (AED)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_iqd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (IQD)'),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Processing Time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
